ifdef CONFIG_OEM_DEBUG_SUPPORT
obj-$(CONFIG_OEM_SYSRQ_X) += sysrq_x.o
endif
ifdef CONFIG_OEM_DEBUG_SUPPORT
# oem trace
obj-$(CONFIG_OEM_TRACE_SUPPORT) += oem_trace.o
obj-y += boot_mode.o
endif

obj-y += coretech/
